require 'serverspec'

describe file('/opt/sonar/conf/sonar.properties') do
  it { should contain /Generated by Chef/ }
end

ports = [80, 9000, 9001]

ports.each do |port|
    describe port(port) do
        it { should be_listening }
    end
end

describe host('google.com') do
  it { should be_resolvable }
end

describe command('/opt/sonar/bin/linux-x86-64/sonar.sh status') do
	its(:stdout) {should match /SonarQube/}
end

